### ISSUE TITLE
End of Line Sequence

### ISSUE THREAD

**Issue by chuikoffru** [halil07/vscode-ext-nestjs-graphql-crud#1]
Hey, @halil07!

First of all, I want to thanks to you for your great job! 

I'd like to ask you fix End of Line Sequence from CRLF to LF, or make it changable at configuration.
Now, I fix every file manually. It's not such conveniently. 

Best regards

**Comment by halil07** [comment]
Hi. @chuikoffru!
Thanks for feedback 👍 

I'm update to Line sequence. Can you upgrade to new version?

Best regards
